version: '3.9'

services:
  mc-server:
    build: .
    container_name: mc-server

    ports:
      - "8888:25565"

    volumes:
      - ./data:/data

    environment:
      EULA: "TRUE"
      XMX: "2G"
      XMS: "1G"

    stdin_open: true
    tty: true

    restart: unless-stopped
