version: '3.9'

services:
  mc-server:
    build: .
    container_name: mc-server
    ports:
      - "8888:25565"
    volumes:
      - ./data:/data
    environment:
      EULA: "TRUE"
    stdin_open: true
    tty: true
